zombocom/derailed_benchmarks

test/derailed_benchmarks/core_ext/kernel_require_test.rb
I believe this is not intentional?
=> Remove duplicated codes.

test/test_helper.rb
With this we can run separate tests for every file successfully.
=> Setup bundle environment in test_helper.rb

lib/derailed_benchmarks/core_ext/kernel_require.rb
=> Fix space format.

lib/derailed_benchmarks/core_ext/kernel_require.rb
=> Fix typo in comments.

README.md, lib/derailed_benchmarks/require_tree.rb, test/derailed_benchmarks/require_tree_test.rb
http://en.wikipedia.org/wiki/IEEE_1541-2002
=> Use correct IEEE unit for Mebibyte

README.md
=> Grammar edits in README.md

lib/derailed_benchmarks/tasks.rb
=> Use correct IEEE unit for Mebibyte in tasks.rb

README.md
=> A horible typo

README.md
I believe that’s what you meant… 
…and also, thanks for this amazing :gem:
=> Fix logs/ to log/ in README.md

README.md
=> fix minor typo in README

README.md
README update to change mem_over_time to ram_over_time
=> mem_over_time is now ram_over_time

README.md
=> Add missing syntax highlighting to some examples

README.md
issue: https://github.com/schneems/derailed_benchmarks/issues/34
=> Explain the use of PATH_TO_HIT for a subdomain

lib/derailed_benchmarks/tasks.rb
Related to shopify/bootsnap#34
=> Fix bootsnap error

README.md
I had to create a strategy to authenticate with [Clearance](https://github.com/thoughtbot/clearance), thought it would be nice to share it.
=> Clearance authentication example

README.md, gemfiles/rails_6_0.gemfile, lib/derailed_benchmarks/stats_from_dir.rb, lib/derailed_benchmarks/tasks.rb, test/derailed_benchmarks/stats_from_dir_test.rb, test/rails_app/config/environment.rb, test/rails_app/db/schema.rb, test/test_helper.rb
#144 and fix Migrations for tests
=> [close #144] Better statistical test

lib/derailed_benchmarks/core_ext/kernel_require.rb
https://github.com/schneems/derailed_benchmarks/issues/149
https://github.com/rails/rails/issues/37308
=> [changelog skip] Temporary fix for Rails 6 requires

CHANGELOG.md, lib/derailed_benchmarks/tasks.rb
not sure of the intent behind the ensure block but there was no preceding begin and the identation gave no clue so this was just my small fix
=> first commit

.circleci/config.yml, gemfiles/rails_git.gemfile, lib/derailed_benchmarks/load_tasks.rb, test/derailed_test.rb, test/test_helper.rb
circleci:Rails 7 requires Ruby 2.7.0 or newer
=> Fix unit test & circleci

.github/workflows/ci.yml, CHANGELOG.md, derailed_benchmarks.gemspec, lib/derailed_benchmarks.rb
=> dead_end -> syntax_suggest
