- README.md
- lib/derailed_benchmarks/tasks.rb
So that it'll run as suggested
Addresses https://github.com/schneems/derailed_benchmarks/pull/1#issuecomment-70020675
> Namespace rake rack_load task in README and in default output

- lib/derailed_benchmarks/tasks.rb
Stackprof is used in `rake perf:stackprof`, but without it in the
gemspec it won't be installed for those who don't have it already.
> Add stackprof dependency

- README.md
- Rakefile
- bin/derailed
- lib/derailed_benchmarks/core_ext/kernel_require.rb
- lib/derailed_benchmarks/tasks.rb
- test/derailed_benchmarks/require_tree_test.rb
- test/integration/tasks_test.rb
Allows you to get memory use information from gems without having to boot up your app using `$ derailed bundle:mem` command. No longer requires you to have a `perf.rake` file.
Re-wrote readme to be more task oriented.
> Add `$ derailed` command.

- Gemfile.lock
- derailed_benchmarks.gemspec
Relaxing rake dependency to reduce version conflicts, as seen in #29
> Change rake dependency from 10.4 to 10

- README.md
- bin/derailed
- lib/derailed_benchmarks.rb
- lib/derailed_benchmarks/require_tree.rb
- lib/derailed_benchmarks/tasks.rb
- test/derailed_benchmarks/require_tree_test.rb
The same file may be required by several libraries, since Ruby only requires files once, the cost is only associated with the first library to require a file. To make this more visible duplicate entries will list all the parents they belong to. For example both `mail` and `fog` require `mime/types. So it may show up something like this in your app:
```
$ derailed bundle:mem
TOP: 54.1836 MiB
mail: 18.9688 MiB
mime/types: 17.4453 MiB (Also required by: fog/storage)
mail/field: 0.4023 MiB
mail/message: 0.3906 MiB
```
That way you'll know that simply removing the top level library (mail) would not result in a memory reduction. The output is trucated after the first two entries:
```
fog/core: 0.9844 MiB (Also required by: fog/xml, fog/json, and 48 others)
fog/rackspace: 0.957 MiB
fog/joyent: …
```
> Display more info about duplicate requires

- README.md
This removes the query parameters used by tracking tools in order to define the source and medium of the traffic.
> Removes the RubyWeekly tracking information

- derailed_benchmarks.gemspec
When using `derailed` outside of rails, it fails unless `thor` happens to be loaded by something else in the `Gemfile`
Create and `bundle install` following `Gemfile`:
```
source 'https://rubygems.org'
ruby '2.2.2'
gem 'derailed'
gem 'stackprof'
gem 'pg' # <-- some gem I am curious about, but does not depend on thor
```
then
```
➜  perf-play  bundle exec derailed bundle:mem
/Users/eoinkelly/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/derailed_benchmarks-1.0.1/bin/derailed:19:in `require': cannot load such file -- thor (LoadError)
from /Users/eoinkelly/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/derailed_benchmarks-1.0.1/bin/derailed:19:in `<top (required)>'
from /Users/eoinkelly/.rbenv/versions/2.2.2/bin/derailed:23:in `load'
from …
```
> Add thor as an explicit gem dependency

- README.md
Make quotes the same so when paste these two gems to Gemfile, do not need to change if single quote is want one wants.
> Make copy-paste gem to Gemfile smooth [ci skip]

- lib/derailed_benchmarks/tasks.rb
Executing `bundle exec derailed exec perf:test` it's raising an exception because `Benchmark` isn't loaded: 
```
/var/lib/gems/2.1.0/gems/derailed_benchmarks-1.0.1/lib/derailed_benchmarks/tasks.rb:102:in `block (2 levels) in <top (required)>': uninitialized constant Benchmark (NameError)
```
It's solved just requiring it.
> Require benchmark in perf:test task

- README.md
- lib/derailed_benchmarks/tasks.rb
- test/integration/tasks_test.rb
I kept having trouble remembering if a task name referred to memory as
`mem` or `ram`. Seems like something that should be consistent. I prefer
`ram` but `mem` was more frequently used.
> Use consistent names for memory tasks

- CHANGELOG.md
- Gemfile.lock
- README.md
- lib/derailed_benchmarks/auth_helpers/devise.rb
- test/integration/tasks_test.rb
- test/rails_app/perf.rake
Fixes #51 and #35 by allowing a lambda to set a custom user in perf.rake
```ruby
DerailedBenchmarks.auth.user = -> { User.find_or_create!(twitter: "schneems") }
```
I added the new syntax to the README and an integration test to check that it works.
> Set custom auth user using a lambda in perf.rake

- lib/derailed_benchmarks/tasks.rb
The temp file generated, at least on OS X, was invalid in some manner.
It would end up splitting into two files - one that contained the
time stamp and output from `ruby -v` and the other that contained the
rest of the file name. Neither of these files ever had any actual output
recorded to them.
None of the other logs have the ruby version in them so instead of
trying to figure out what characters OS X wasn't liking, I just removed
the ruby version from the name.
> Fix temp file names for ram_over_time

- README.md
The change here is twofold:
1. The previous example was failing
2. It did not account for a very common use case, of the user needing a password to be created
This addresses those issues by using `first_or_create` which will still take advantage of a finding a user by the specific criteria, if there is one on the db, or it will give you one in the block so you can play around with it and set the attributes you need.
I believe this is better of a default than #54, thus a different PR to solve the same issue.
> Improve devise authentication example

- README.md
- bin/derailed
- lib/derailed_benchmarks/tasks.rb
This lets you set the environment variable `DERAILED_SKIP_ACTIVE_RECORD=true` if you aren't using ActiveRecord as your ORM.
I wasn't sure what the best place to add documentation for this would be - let me know and I'll add it.
> Add environment variable check before using ActiveRecord

- lib/derailed_benchmarks/tasks.rb
If `ENV['LOG_LEVEL']` is present, do not set it to "FATAL" (for setting custom levels).
> Leep log level if defined

- lib/derailed_benchmarks/tasks.rb
Basically to save us from below error.
**No such file or directory @ rb_sysopen - tmp/2015-10-05T21:49:15-07:00-heap.dump (Errno::ENOENT)** .  I removed the `/tmp` folder sometime back and gave this error on `bundle exec derailed exec perf:heap`
```ruby
Booting: production
db/production.sqlite3 already exists
Endpoint: "/"
/Users/agupta/.rvm/gems/ruby-2.2.2/gems/derailed_benchmarks-1.1.2/lib/derailed_benchmarks/tasks.rb:72: warning: already initialized constant DERAILED_APP
/Users/agupta/.rvm/gems/ruby-2.2.2/gems/derailed_benchmarks-1.1.2/lib/derailed_benchmarks/tasks.rb:23: warning: previous definition of DERAILED_APP was here
Running 1000 times
Heap file generated: "tmp/2015-10-05T21:49:15-07:00-heap.dump"
/Users/agupta/.rvm/gems/ruby-2.2.2/gems/derailed_benchmarks-1.1.2/lib/derailed_ben …
```
> Create /tmp directory if doesn't exist

- README.md
`mime/types/columnar` wasn’t added until 2.6.1.
> Fix recommended mime-types require

- .travis.yml
- derailed_benchmarks.gemspec
Updates the minimum Ruby version to be newer than 2.1.0 since the
following dependencies need to be met:
- memory_profiler wants >= 2.1.0
- rack wants >= 2.2.0
This also updates CI to only run the newer versions of Ruby since < 2.1
shouldn't work anyway and there is no point having "allowed failures" if
it will always fail.
Updated with feedback from #87
> Add minimum Ruby version to gemspec

- lib/derailed_benchmarks/tasks.rb
This task is not used/documented.
Fixes #97
> Remove task `:foo` from tasks.rb

- README.md
- lib/derailed_benchmarks/tasks.rb
- test/integration/tasks_test.rb
- test/rails_app/app/controllers/pages_controller.rb
- test/rails_app/config/routes.rb
This PR adds support to for passing HTTP headers. Both internal Rack requests and USE_SERVER is supported.
I added this while benchmarking API endpoints, which require some specific HTTP headers.
> support passing HTTP headers via ENV

- README.md
The word usage was mispelled.
Thank You for derailed benchmarl
> Typo for the word usage

- test/rails_app/app/controllers/application_controller.rb
- test/rails_app/app/controllers/authenticated_controller.rb
- test/rails_app/db/migrate/20141210070547_devise_create_users.rb
Don't use `before_filter` for test rails_app since Rails changed `before_filter` to become `before_action`, so prefer using that over before_filter (since it has been removed in the [newest versions of Rails](https://github.com/rails/rails/blob/158742e/actionpack/CHANGELOG.md).
> Remove deprecated methods `skip_action_callback`, `skip_filter`, `before_filter`, `prepend_before_filter`, `skip_before_filter`, `append_before_filter`, `around_filter` `prepend_around_filter`, `skip_around_filter`, `append_around_filter`, `after_filter`, `prepend_after_filter`, `skip_after_filter` and `append_after_filter`.
> 
> Rafael Mendonça França
Also, since we are making `before_action` backwards compatible for older versions of Rails where `before_filter` was the only method available, move that alias …
> Fix travis tests for Rails 5.1+

- README.md
- lib/derailed_benchmarks/tasks.rb
- test/integration/tasks_test.rb
When testing with a system that uses jit is often times desirable to “warm up” the code to test that optimizations applied after jit has run are faster.
https://twitter.com/samsaffron/status/971531146956697601
This PR allows an app to be called X times before being measured by supplying the environment variable `WARM_COUNT` with any number greater than 0. For example `WARM_COUNT=5000` will hit the app 5000 times before measurements are started. 
Default warm up is 0 so original behavior is preserved.
> Allow warm up before recording data

- lib/derailed_benchmarks/tasks.rb
I would like to remove the following warning message:
```
/home/k0kubun/src/github.com/schneems/derailed_benchmarks/lib/derailed_benchmarks/tasks.rb:86: warning: already initialized constant DERAILED_APP
/home/k0kubun/src/github.com/schneems/derailed_benchmarks/lib/derailed_benchmarks/tasks.rb:23: warning: previous definition of DERAILED_APP was here
```
> Fix "already initialized constant" warning

- lib/derailed_benchmarks/tasks.rb
Use `exit(1)` instead of `raise` when the app responds with an error. We want this because the latter causes bundler to think that there's a bug in the `derailed` command, and you get the error message indicated in #112.
Closes #112.
> Better error raising

- lib/derailed_benchmarks/core_ext/kernel_require.rb
There is a code in rails in DeprecationProxy that undef methods of
deprecated object, constant, etc. But in our case we were making
"require" public so it was undefined and it was leading to a crash.
Fix: https://github.com/schneems/derailed_benchmarks/issues/128
Related:
- https://github.com/schneems/derailed_benchmarks/pull/130
- https://github.com/rails/rails/pull/36530
> Prevent undefining "require" by making it private

- README.md
- lib/derailed_benchmarks/stats_from_dir.rb
- lib/derailed_benchmarks/stats_in_file.rb
- lib/derailed_benchmarks/tasks.rb
- test/derailed_benchmarks/stats_from_dir_test.rb
- test/integration/tasks_test.rb
There were some problems to the old formatting of the library comparison
output. The x faster and % faster were confusing because it wasn't clear
how they were derived. Also it was not clear which commit SHA belonged
to which values.
In this updated value we give the formulas for the values that are being
shown as well. The latest commit is always first and the value will show
either SLOWER or FASTER based on actual values. Finally we're including
the git first line description to make it clearer which commit is which.
New output looks like this:
```
❤️ ❤️ ❤️  (Statistically Significant) ❤️ ❤️ ❤️
[7b4d80cb37] "1.8x Faster Partial Caching - Faster Cache Keys" - (10.9711965 seconds)
FASTER by:
1.0870x [older/newer]
8.0026% [(older - newer) / older * 100]
[13d6aa3a7b] "Merge pull request …
```
> Add commit description and ordering to output

- README.md
- lib/derailed_benchmarks/tasks.rb
The most common case will be to test the last to git SHAs, so when the
env var does not specify specific commits, we will default to the last
two in the git repo.
> Default perf:library to last two commits

- README.md
- gemfiles/rails_git.gemfile
- lib/derailed_benchmarks/stats_from_dir.rb
- lib/derailed_benchmarks/stats_in_file.rb
- lib/derailed_benchmarks/tasks.rb
- test/derailed_benchmarks/stats_from_dir_test.rb
- test/integration/tasks_test.rb
By default perf:library will not stop when it detects 10 runs that are
statistically significant. This provides an average that is not as
accurate, but decreases the time to run a benchmark from 60+ minutes per
run to as little as 3 minutes and results are roughly comparable. This
setting can also be tuned so that all benchmark iterations are forced to
run.
In addition, one SHA can be specified instead of 2. When this is
provided then derailed will assume you want this SHA run against the
most recent commit present. This could be useful if you are trying out
different changes on a branch and want to always compare the same
baseline to the latest commit in your branch.
> Better defaults for perf:library

- lib/derailed_benchmarks/core_ext/kernel_require.rb
- test/derailed_benchmarks/core_ext/kernel_require_test.rb
- test/fixtures/require/parent_one.rb
- test/fixtures/require/relative_child_two.rb
Ruby's `require_relative` [converts paths to absolute paths][1] before
calling `require`. This conversion effectively means that you can pass
an absolute path to `require_relative` and have it load the file
correctly, as if it were a relative path.
This is an idiosyncrasy of Ruby that doesn't match the semantics of the
method. However, some libraries, like [grpc][2], rely on the
idiosyncrasy to load files. Because Derailed's implementation doesn't
conform to this idiosyncrasy, it is unable to work when such libraries
exist in a project.
This change makes Derailed's implementation of `require_relative` behave
more closely to the implementation in Ruby. By making this change, you
can use Derailed with any offending gem.
[1]: https://github.com/ruby/ruby/blob/v2_6_3/load.c#L832-L841
[2]: …
> Allow `require_relative` to accept absolute paths

- CHANGELOG.md
- README.md
- lib/derailed_benchmarks/tasks.rb
I was finding that 5 seconds was not long enough for me to feel comfortable with the results with my `perf:ips`, so I added the ability to configure the  `Benchmark.ips` test run via environment variables. I prefixed each of them with `IPS_*` since they we specific only to this test.
I didn't immediately see a place to add tests for this, but if you like the PR and can point me to it. I'll add them.
> Allow config of `Benchmark.ips` via env vars

- CHANGELOG.md
- lib/derailed_benchmarks/tasks.rb
When using perf:library there was a bug that would result in the same sha being tested twice for instance if you ran:
```
$ SHAS_TO_TEST='schneems/keymaster-more-compat-correct' bundle exec derailed exec perf:library
```
Then it would incorrectly default to the same SHA. This PR fixes that behavior, it also detects this failure mode and raises an error if it happens somehow (perhaps the user accidentally puts it in twice somehow).
In addition there's a nice litte testing output that advertises which sha and description you're testing before you execute the tests:
```
Testing 1: fe60c15579: Preserve existing interfaces for smaller diff
Testing 2: 430579e40b: 1.8x Faster Partial Caching - Faster Cache Keys
```
> Guard, and fix single sha perf:library tests

- README.md
- lib/derailed_benchmarks/tasks.rb
While using `perf:library` I found that I wanted to know what directory a given test run was stored in. So now the output looks like this:
```
👎👎👎(NOT Statistically Significant) 👎👎👎
[3054e1d584] "Merge pull request #36506 from kamipo/group_by_with_order_by_virtual_count_attribute" - (0.017138 seconds)
SLOWER by:
0.9702x [older/newer]
-3.0764% [(older - newer) / older * 100]
[80f989aece] "Remove duplicated attribute alias resolution in `_select!`" - (0.0166265 seconds)
Iterations per sample: 10
Samples: 2
Test type: Kolmogorov Smirnov
Is significant? (max > critical): false
D max: 0.5
D critical: 1.2238734153404083
Output: tmp/compare_branches/2019-12-16-21-20-1576552858-200576000/results.txt
```
> Note the file in the bottom which has the directory name …
> [changelog skip] Fix bug and add extra output to `perf:library`

- CHANGELOG.md
- lib/derailed_benchmarks/stats_from_dir.rb
- lib/derailed_benchmarks/stats_in_file.rb
- lib/derailed_benchmarks/version.rb
- test/derailed_benchmarks/stats_from_dir_test.rb
Since we don't know the shape of the distribution we're dealing with, it's better to use the median value rather than the average for comparisons
Also adding some alignment so that 
```
[3054e1d584] "Merge pull request #36506 from kamipo/group_by_with_order_by_virtual_count_attribute" - (0.016381 seconds)
SLOWER by:
0.9697x [older/newer]
-3.1224% [(older - newer) / older * 100]
```
Will become:
```
[3054e1d584] "Merge pull request #36506 from kamipo/group_by_with_order_by_virtual_count_attribute" - (0.016381 seconds)
SLOWER by:
0.9697x [older/newer]
-3.1224% [(older - newer) / older * 100]
```
(Minor, but it was really bugging me)
Also added emojis for faster and slower:
```
SLOWER 🐢🐢🐢 by:
```
Which helps to visually distinguish results.
> Use median over average

- CHANGELOG.md
- README.md
- lib/derailed_benchmarks/tasks.rb
The goal of adding the statistical significane check was to determine if it was "safe" to stop early, but this method of constantly checking for significance and then stopping produces less than stellar results. It's better to default to running the full test.
As a compromise the intermediate results are also output so if someone wants to use this as a quick and dirty guide for if they're on the right track or not, they can but they should know it might not hold up to scrutiny.
> Don't use statistical significance as a stopping condition

- CHANGELOG.md
- lib/derailed_benchmarks/stats_from_dir.rb
- test/derailed_benchmarks/stats_from_dir_test.rb
I want to know if a patch stands up to a more rigorous statistical check. Instead of forcing the user to specify what confidence interval they want, we default to 95% then if it passes we try to check again at 99%. 
If the 99% check fails then we rely on the 95% check, but note the different confidence interval in the output.
> Check multiple confidence intervals

- CHANGELOG.md
- README.md
- lib/derailed_benchmarks/tasks.rb
- test/integration/tasks_test.rb
Currently, this only supports libraries if the user inputs the env variable. Now, we can take the current directory and run the performance tests comparing the two previous commits there.
CC: @schneems
> Generalizing to the current directory to support all libraries, not just rails

- CHANGELOG.md
- derailed_benchmarks.gemspec
bump rails requirement for < 7 and rails 6.1.0.alpha now requires thor ~> 1.0.
> Support Rails 6.x and bump thor requirement

- CHANGELOG.md
- lib/derailed_benchmarks/core_ext/kernel_require.rb
- lib/derailed_benchmarks/load_tasks.rb
- test/integration/tasks_test.rb
- test/rails_app/config/application.rb
@schneems I was having trouble running `perf:mem` when Zeitwerk is enabled.
I'm getting an infinite loop on the `require` because Zeitwerk also patches `require`:
```ruby
/builds/gitlab-org/gitlab/vendor/ruby/2.6.0/gems/derailed_benchmarks-1.6.0/lib/derailed_benchmarks/core_ext/kernel_require.rb:21:in `require'
/builds/gitlab-org/gitlab/vendor/ruby/2.6.0/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:23:in `require'
/builds/gitlab-org/gitlab/vendor/ruby/2.6.0/gems/derailed_benchmarks-1.6.0/lib/derailed_benchmarks/core_ext/kernel_require.rb:21:in `require'
/builds/gitlab-org/gitlab/vendor/ruby/2.6.0/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:23:in `require'
/builds/gitlab-org/gitlab/vendor/ruby/2.6.0/gems/derailed_benchmarks-1.6.0/lib/derailed_benchmarks/core_ext/kernel_require.rb:21:in …
```
> Fix infinite loop when Zeitwerk is enabled

- CHANGELOG.md
- derailed_benchmarks.gemspec
- lib/derailed_benchmarks/stats_from_dir.rb
- lib/derailed_benchmarks/tasks.rb
- test/derailed_benchmarks/stats_from_dir_test.rb
Turns out that reducing a whole bunch of numbers to a single value (average for example, or median) means that we're getting rid of a huge amount of information. One way to add context back in without drowning users in raw data is to include a histogram in the output. 
With histograms in the output the user can see the distributions of their two runs to make better informed decisions about the validity of the data.
Here's an example histogram:
```
Histogram
┌                                        ┐
[3.1, 3.2) ┤▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 23
[3.2, 3.3) ┤▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 14
[3.3, 3.4) ┤▇▇▇▇▇▇▇▇ 5
[3.4, 3.5) ┤▇▇▇▇▇ 3
[3.5, 3.6) ┤▇▇ 1
[3.6, 3.7) ┤▇▇▇▇▇▇▇▇ 5
[3.7, 3.8) ┤▇▇▇▇▇▇▇▇▇▇▇▇▇ 8
[3.8, 3.9) ┤▇▇▇ 2
└                                        ┘
Frequency
```
Here's how the …
> Add histogram to output

- .travis.yml
- CHANGELOG.md
- README.md
- derailed_benchmarks.gemspec
- lib/derailed_benchmarks/require_tree.rb
- lib/derailed_benchmarks/stats_from_dir.rb
- test/derailed_benchmarks/stats_from_dir_test.rb
- test/fixtures/require/child_one.rb
- test/fixtures/require/child_two.rb
- test/fixtures/require/parent_one.rb
Mostly as a response to https://github.com/schneems/derailed_benchmarks/issues/176#issuecomment-692615307
I want to follow Heroku's support. Heroku-16 provides Ruby 2.2 as the oldest version available. I want people on older rubies to find and fix perf issues on their apps where possible.
> Explicit 2.2.0+ support

- CHANGELOG.md
- lib/derailed_benchmarks/load_tasks.rb
The command in backticks only returns a string so no `.body` method is available. `response` is a string so we can write it to the file directly.
> Correct logging of unsuccessful curl requests to file

- CHANGELOG.md
- README.md
- derailed_benchmarks.gemspec
- lib/derailed_benchmarks/stats_from_dir.rb
- test/derailed_benchmarks/stats_from_dir_test.rb
In an effort to make comparing distributions easier this PR puts the histogram data in a side-by-side format. The goal was a very loose approximation of a Violin plot https://en.wikipedia.org/wiki/Violin_plot.
Here's an example:
```
❤️ ❤️ ❤️  (Statistically Significant) ❤️ ❤️ ❤️
[f1ab117] (11.3844 seconds) "I am the new commit" ref: "winner"
FASTER 🚀🚀🚀 by:
1.0062x [older/newer]
0.6147% [(older - newer) / older * 100]
[5594a2d] (11.4548 seconds) "Old commit" ref: "loser"
Iterations per sample:
Samples: 100
Test type: Kolmogorov Smirnov
Confidence level: 99.0 %
Is significant? (max > critical): true
D critical: 0.2145966026289347
D max: 0.26
Histograms (time ranges are in seconds):
[f1ab117] description:                                        [5594a2d] description:
"I am the new commit" …
```
> Print out histograms side-by-side

- derailed_benchmarks.gemspec
On December 1st `memory_profiler 1.0` was released, with various optimizations: https://github.com/SamSaffron/memory_profiler/blob/master/CHANGELOG.md#100---02-12-2020
This new version of memory profiler removes support for Ruby 2.3 and Ruy 2.4.
Support for Ruby 2.2 (which `derailed_benchmarks` supports) was removed by version `0.9.13` which the current gemspec allows
> Add support for memory_profiler 1.0

- CHANGELOG.md
- README.md
- lib/derailed_benchmarks/tasks.rb
- test/derailed_test.rb
- test/integration/tasks_test.rb
Hi,
Thanks for the great tool, we just cleared out a significant memory leak in our app ! However, to do so we also needed a diff between heaps for a better view of what is retained. Since you mention SamSaffron in some parts of your repositories (for instance in heapy's README), I guessed this would be an ok addition.
I've tried to use a similar style and design as other tasks, please tell me if you need any change.
Articles I've cited seems great to me to, but please tell me if you prefer any other resource (which I may discover in the process :smile:)
> Add `perf:heap_diff` tool

- CHANGELOG.md
- bin/derailed
Thor 1.0.0([CHANGELOG](https://github.com/rails/thor/blob/fb625b223465692a9d8a88cc2a483e126f1a8978/CHANGELOG.md#100)) has deprecated the behavior of relying on default `exit_on_failure?` Hence, making the devs define this method. 
Thor [#621](https://github.com/rails/thor/pull/621), [#625](https://github.com/rails/thor/pull/625)
PRIOR TO CHANGE:
```
bundle exec derailed exec perf:mem_over_time development
ERROR: "derailed exec" was called with arguments ["perf:mem_over_time", "development"]
Usage: "derailed exec"
Deprecation warning: Thor exit with status 0 on errors. To keep this behavior, you must define `exit_on_failure?` in `DerailedBenchmarkCLI`
You can silence deprecations warning by setting the environment variable THOR_SILENCE_DEPRECATION.
```
AFTER:
```
bundle exec derailed exec …
```
> Fix Thor's deprecation error

- README.md
- lib/derailed_benchmarks/tasks.rb
As mentionned in a previous PR (https://github.com/schneems/derailed_benchmarks/pull/193#issuecomment-838863582), here's the up-to-date (hopefully clear enough!) article on memory leaks. Also [published to r/ruby](https://www.reddit.com/r/ruby/comments/og3fx4/tracking_a_ruby_memory_leak_in_2021/) as you suggested :)
I've also fixed a typo I made in my previous PR 😅 
Best,
Ulysse
> Update article reference for heap_diff

- README.md
- bin/derailed
- Remove initial action mailer require, per https://github.com/zombocom/derailed_benchmarks/pull/60#issuecomment-169848795
- Add an ENV var that allows you to not do any additional requires here, so that it's all handled by the Rails app
The new ENV is useful if you want to do stuff like this in `config/application.rb`:
Currently `derailed` will still report some of the gems as being used even if they are not, since it requires them itself!
> Allow running tasks without requiring all/any of rails

- CHANGELOG.md
- derailed_benchmarks.gemspec
This reduces unnecessary redirection when someone visits this gem's homepage via https://rubygems.org/gems/derailed_benchmarks some tools or APIs that use the gem's metadata.
> Update the gemspec's homepage to the current repo URL

- lib/derailed_benchmarks/load_tasks.rb
was getting:
/Users/dorianmariefr/.rvm/gems/ruby-3.0.3/gems/derailed_benchmarks-2.1.1/lib/derailed_benchmarks/load_tasks.rb:48:in `block (2 levels) in <top (required)>': undefined method `migrate' for ActiveRecord::Migrator:Class (NoMethodError)
> support rails 7 for `bundle exec derailed exec mem`

- derailed_benchmarks.gemspec
- lib/derailed_benchmarks/stats_from_dir.rb
Pull request to replace the current require for `statistics` gem for `ruby-statistics`. I've updated the `gemspec` but I did not update the gem version for a breaking change version. Let me know if you want me to amend this PR and changing the version.
Not sure if happen to other but running a Rails app 7.2 version failed due to this change on` ruby-statistics`.
[ISSUE-237](https://github.com/zombocom/derailed_benchmarks/issues/237)
> Replace statistics require for ruby-statistics as it fails on Rails 7.2

- derailed_benchmarks.gemspec
- lib/derailed_benchmarks/stats_from_dir.rb
as mentioned in the issue
https://github.com/zombocom/derailed_benchmarks/issues/237 by @espen, the `ruby-statistics` gem updated the namespace of their gem from `statistics` to `ruby-statistics`
https://github.com/estebanz01/ruby-statistics/commit/baadc9fd3bd90c9ed14e2bba48b8eb806bfe1ff2 and
https://github.com/estebanz01/ruby-statistics/commit/00312b9a329c742c2b851a182d3ab35bb86fe535 this commit is addressing the change
> update requirement in `lib/derailed_benchamrks/stats_from_dir.rb`

- .devcontainer/devcontainer.json
- .github/workflows/ci.yml
- CHANGELOG.md
- Gemfile
- derailed_benchmarks.gemspec
- gemfiles/rails_6_0.gemfile
- gemfiles/rails_6_1.gemfile
- gemfiles/rails_7_0.gemfile
- gemfiles/rails_head.gemfile
- lib/derailed_benchmarks/load_tasks.rb
- lib/derailed_benchmarks/stats_from_dir.rb
- test/integration/tasks_test.rb
- test/test_helper.rb
Changes: 
- mostly just fixing some bitrot with (mostly) minimal changes. tried to fix up any warnings whenever possible because its hard to spelunk through test logs when its super verbose.
- followup to #238 and #239 - make sure those changes account for ruby < 3.0 (which werent caught because tests were broken)
TODO:
- needs a followup to get more recent rails point releases in the matrix
see inline for specific notes
> get tests working again

- .gitignore
- CHANGELOG.md
- README.md
- derailed_benchmarks.gemspec
- lib/derailed_benchmarks/load_tasks.rb
- test/integration/tasks_test.rb
- test/rails_app/app/controllers/users_controller.rb
- test/rails_app/config/environments/development.rb
- test/rails_app/config/environments/production.rb
- test/rails_app/config/environments/test.rb
- test/rails_app/config/routes.rb
This PR is literally a copy-pasta of changes made by @mateusg in this older PR, with merge conflicts being resolved: https://github.com/zombocom/derailed_benchmarks/pull/122/files
All credit goes to @mateusg.
Feel free to close this if the old PR gets merged.
> [Updated] Add support for non-GET requests

- .github/workflows/ci.yml
- CHANGELOG.md
- gemfiles/rails_head.gemfile
- test/integration/tasks_test.rb
- test/test_helper.rb
- fixes #226
- update all relevant examples to indicate pwd is no longer mandatory
- reduce test verbosity, making it easier to scan for issues
- remove duplicate `require` in `test_helper` that obscures when `rails/test_help` is actually loaded
> support relative gemfile reference when running tests

- CHANGELOG.md
add missing changelog entry (fixes #237) and normalize styling
> Update CHANGELOG.md [ci skip]

- derailed_benchmarks.gemspec
- Fixed the logic in the gemspec file to correctly compare the current Ruby version with the required version.
- Replaced string comparison of `RUBY_VERSION` with `Gem::Version` for better semantic version handling.
- Addressed edge cases, such as "3.10" being greater than "3.2".
- Adds flexibility for the syntax_suggest gem version to allow 2.x for Ruby 3.0 & 3.1 (related: #258)
Why:
The previous comparison caused a `LoadError` for `syntax_suggest` on Ruby 3.1.6 due to string-based version comparison. RUBY_VERSION returns a string, not a comparable version, breaking the current comparison in some cases.
> Fix gemspec ruby version checks
